### ISSUE TITLE
Having trouble to authorize cli access

### ISSUE THREAD

**Issue by TekniskSupport** [SmartThingsCommunity/smartthings-cli#87]
I downloaded the binary and trying to get it to work.

I'm having trouble authorizing access for cli, when I run any command it pops up my browser and i authenticate and grant access. Then I get a message that states that I can close the window, but nothing happens in the command prompt (just ticking dots) 

Any advice?

Environment:
 - `Ubuntu 18.04` 
 - `smartthings/cli/0.0.0-pre.6 linux-x64 node-v12.18.1`
 - I'm authenticating using Samsung account.
 - I have 2FA activated.
 
![image](https://user-images.githubusercontent.com/13868526/89711187-f8225280-d988-11ea-9efc-630befa733b1.png)

![image](https://user-images.githubusercontent.com/13868526/89711196-040e1480-d989-11ea-92d2-1a69b56b6180.png)

![image](https://user-images.githubusercontent.com/13868526/89711205-0ff9d680-d989-11ea-8417-fd1cdb8cb50b.png)

**Comment by TekniskSupport** [comment]
I Tried compiling 0.7pre version and upgrading node to 12.18.3 but i still have the same result.

**Comment by rossiam** [comment]
My guess is you're running into a bug we've recently found (that should be fixed soon) where the config directory isn't created automatically. Try `mkdir -p ~/.config/@smartthings` and the running it again.

**Comment by TekniskSupport** [comment]
Hi @rossiam 

Thank you for your reply! 
That did not solve the issue, however it got me on the right track, i investigated a little bit further and found the correct directory was
`~/.config/@smartthings/cli`

I created it and now it works. just wanted to note the correct solution in the issue.
Thanks again!

**Comment by rossiam** [comment]
Thanks for the directory correction. The real fix has been released now.
